name: Minesweeper
description: "An implementation of the classical Mineswepper game from Windows."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  format: ^1.4.0
  shared_preferences: ^2.2.2
  vibration: ^1.8.4
  fullscreen_window: ^1.0.4
  vector_math: ^2.1.4
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
